<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- Die Konfiguration muss neben der fertigen NLogDemo.dll liegen -->
    <None Update="nlog.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
